// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.6
// source: imu/imu.proto

package imu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 6-axis inertial messurment unit
type IMU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// в роборуке 3 IMU, расположенных ортогонально друг другу
	XAccel float32 `protobuf:"fixed32,2,opt,name=xAccel,proto3" json:"xAccel,omitempty"`
	// измеренное ускорение по оси x
	YAccel float32 `protobuf:"fixed32,3,opt,name=yAccel,proto3" json:"yAccel,omitempty"`
	// измеренное ускорение по оси y
	ZAccel float32 `protobuf:"fixed32,4,opt,name=zAccel,proto3" json:"zAccel,omitempty"`
	// измеренное ускорение по оси z
	XAngle float32 `protobuf:"fixed32,5,opt,name=xAngle,proto3" json:"xAngle,omitempty"`
	// измеренное угла наклона по оси x
	YAngle float32 `protobuf:"fixed32,6,opt,name=yAngle,proto3" json:"yAngle,omitempty"`
	// измеренное угла наклона по оси y
	ZAngle float32 `protobuf:"fixed32,7,opt,name=zAngle,proto3" json:"zAngle,omitempty"`
	// измеренное угла наклона по оси z
	ConnectionPin string `protobuf:"bytes,8,opt,name=connectionPin,proto3" json:"connectionPin,omitempty"` // Пин (порт на плате) к которому будет крепиться датчик IMU
}

func (x *IMU) Reset() {
	*x = IMU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imu_imu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IMU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMU) ProtoMessage() {}

func (x *IMU) ProtoReflect() protoreflect.Message {
	mi := &file_imu_imu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMU.ProtoReflect.Descriptor instead.
func (*IMU) Descriptor() ([]byte, []int) {
	return file_imu_imu_proto_rawDescGZIP(), []int{0}
}

func (x *IMU) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *IMU) GetXAccel() float32 {
	if x != nil {
		return x.XAccel
	}
	return 0
}

func (x *IMU) GetYAccel() float32 {
	if x != nil {
		return x.YAccel
	}
	return 0
}

func (x *IMU) GetZAccel() float32 {
	if x != nil {
		return x.ZAccel
	}
	return 0
}

func (x *IMU) GetXAngle() float32 {
	if x != nil {
		return x.XAngle
	}
	return 0
}

func (x *IMU) GetYAngle() float32 {
	if x != nil {
		return x.YAngle
	}
	return 0
}

func (x *IMU) GetZAngle() float32 {
	if x != nil {
		return x.ZAngle
	}
	return 0
}

func (x *IMU) GetConnectionPin() string {
	if x != nil {
		return x.ConnectionPin
	}
	return ""
}

// отфильтрованные данные, вычисленные с опорой на все 3 IMU
type ResultIMU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XAccel float32 `protobuf:"fixed32,1,opt,name=xAccel,proto3" json:"xAccel,omitempty"`
	// измеренное ускорение по оси x
	YAccel float32 `protobuf:"fixed32,2,opt,name=yAccel,proto3" json:"yAccel,omitempty"`
	// измеренное ускорение по оси y
	ZAccel float32 `protobuf:"fixed32,3,opt,name=zAccel,proto3" json:"zAccel,omitempty"` //измеренное ускорение по оси z
}

func (x *ResultIMU) Reset() {
	*x = ResultIMU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imu_imu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultIMU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultIMU) ProtoMessage() {}

func (x *ResultIMU) ProtoReflect() protoreflect.Message {
	mi := &file_imu_imu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultIMU.ProtoReflect.Descriptor instead.
func (*ResultIMU) Descriptor() ([]byte, []int) {
	return file_imu_imu_proto_rawDescGZIP(), []int{1}
}

func (x *ResultIMU) GetXAccel() float32 {
	if x != nil {
		return x.XAccel
	}
	return 0
}

func (x *ResultIMU) GetYAccel() float32 {
	if x != nil {
		return x.YAccel
	}
	return 0
}

func (x *ResultIMU) GetZAccel() float32 {
	if x != nil {
		return x.ZAccel
	}
	return 0
}

var File_imu_imu_proto protoreflect.FileDescriptor

var file_imu_imu_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x75, 0x2f, 0x69, 0x6d, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x49, 0x6d, 0x75, 0x22, 0xd3, 0x01, 0x0a, 0x03, 0x49, 0x4d, 0x55, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x78, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x78, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x79, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x79, 0x41,
	0x63, 0x63, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x7a, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x78, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x78, 0x41,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x79, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x79, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x7a, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x7a, 0x41,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x22, 0x53, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x49, 0x4d, 0x55, 0x12, 0x16, 0x0a, 0x06, 0x78, 0x41, 0x63, 0x63, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x78, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x79, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x79, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x7a, 0x41, 0x63, 0x63, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x7a, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x42,
	0x1e, 0x5a, 0x1c, 0x42, 0x69, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x57, 0x65, 0x62, 0x2d, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x75, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imu_imu_proto_rawDescOnce sync.Once
	file_imu_imu_proto_rawDescData = file_imu_imu_proto_rawDesc
)

func file_imu_imu_proto_rawDescGZIP() []byte {
	file_imu_imu_proto_rawDescOnce.Do(func() {
		file_imu_imu_proto_rawDescData = protoimpl.X.CompressGZIP(file_imu_imu_proto_rawDescData)
	})
	return file_imu_imu_proto_rawDescData
}

var file_imu_imu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_imu_imu_proto_goTypes = []interface{}{
	(*IMU)(nil),       // 0: Imu.IMU
	(*ResultIMU)(nil), // 1: Imu.ResultIMU
}
var file_imu_imu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imu_imu_proto_init() }
func file_imu_imu_proto_init() {
	if File_imu_imu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imu_imu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IMU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imu_imu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultIMU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imu_imu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imu_imu_proto_goTypes,
		DependencyIndexes: file_imu_imu_proto_depIdxs,
		MessageInfos:      file_imu_imu_proto_msgTypes,
	}.Build()
	File_imu_imu_proto = out.File
	file_imu_imu_proto_rawDesc = nil
	file_imu_imu_proto_goTypes = nil
	file_imu_imu_proto_depIdxs = nil
}
