// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.6
// source: potentiometer/potentiometer.proto

package potentiometer

import (
	shared "Bionic-Web-Control/proto/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position int32

const (
	Position_p0 Position = 0 //первый сустав
	// (между кистью и первой фалангой), в случае с большим - привение
	Position_p1 Position = 1 //второй сустав
	// (между первой и второй фалангами), в случае с большим - между кистью и первой фалангой
	Position_p2 Position = 2 //третий сустав
)

// Enum value maps for Position.
var (
	Position_name = map[int32]string{
		0: "p0",
		1: "p1",
		2: "p2",
	}
	Position_value = map[string]int32{
		"p0": 0,
		"p1": 1,
		"p2": 2,
	}
)

func (x Position) Enum() *Position {
	p := new(Position)
	*p = x
	return p
}

func (x Position) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Position) Descriptor() protoreflect.EnumDescriptor {
	return file_potentiometer_potentiometer_proto_enumTypes[0].Descriptor()
}

func (Position) Type() protoreflect.EnumType {
	return &file_potentiometer_potentiometer_proto_enumTypes[0]
}

func (x Position) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Position.Descriptor instead.
func (Position) EnumDescriptor() ([]byte, []int) {
	return file_potentiometer_potentiometer_proto_rawDescGZIP(), []int{0}
}

// измерение угла в суставе
type Potentiometer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Finger        shared.Finger `protobuf:"varint,1,opt,name=finger,proto3,enum=Shared.Finger" json:"finger,omitempty"`              //Какой палец
	Positoin      Position      `protobuf:"varint,2,opt,name=positoin,proto3,enum=Potentiometer.Position" json:"positoin,omitempty"` //Позиция потенцометра
	Angle         uint32        `protobuf:"varint,3,opt,name=angle,proto3" json:"angle,omitempty"`                                   //Угол, измеренный потенциометром
	ConnectionPin string        `protobuf:"bytes,4,opt,name=connectionPin,proto3" json:"connectionPin,omitempty"`                    // Пин (порт на плате) к которому будет крепиться датчик потенциометра
}

func (x *Potentiometer) Reset() {
	*x = Potentiometer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_potentiometer_potentiometer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Potentiometer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Potentiometer) ProtoMessage() {}

func (x *Potentiometer) ProtoReflect() protoreflect.Message {
	mi := &file_potentiometer_potentiometer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Potentiometer.ProtoReflect.Descriptor instead.
func (*Potentiometer) Descriptor() ([]byte, []int) {
	return file_potentiometer_potentiometer_proto_rawDescGZIP(), []int{0}
}

func (x *Potentiometer) GetFinger() shared.Finger {
	if x != nil {
		return x.Finger
	}
	return shared.Finger(0)
}

func (x *Potentiometer) GetPositoin() Position {
	if x != nil {
		return x.Positoin
	}
	return Position_p0
}

func (x *Potentiometer) GetAngle() uint32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Potentiometer) GetConnectionPin() string {
	if x != nil {
		return x.ConnectionPin
	}
	return ""
}

var File_potentiometer_potentiometer_proto protoreflect.FileDescriptor

var file_potentiometer_potentiometer_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2f,
	0x70, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x1a, 0x13, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x66, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x50, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x69, 0x6e, 0x2a, 0x22, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06,
	0x0a, 0x02, 0x70, 0x30, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x70, 0x31, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x70, 0x32, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x42, 0x69, 0x6f, 0x6e, 0x69, 0x63,
	0x2d, 0x57, 0x65, 0x62, 0x2d, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_potentiometer_potentiometer_proto_rawDescOnce sync.Once
	file_potentiometer_potentiometer_proto_rawDescData = file_potentiometer_potentiometer_proto_rawDesc
)

func file_potentiometer_potentiometer_proto_rawDescGZIP() []byte {
	file_potentiometer_potentiometer_proto_rawDescOnce.Do(func() {
		file_potentiometer_potentiometer_proto_rawDescData = protoimpl.X.CompressGZIP(file_potentiometer_potentiometer_proto_rawDescData)
	})
	return file_potentiometer_potentiometer_proto_rawDescData
}

var file_potentiometer_potentiometer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_potentiometer_potentiometer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_potentiometer_potentiometer_proto_goTypes = []interface{}{
	(Position)(0),         // 0: Potentiometer.Position
	(*Potentiometer)(nil), // 1: Potentiometer.Potentiometer
	(shared.Finger)(0),    // 2: Shared.Finger
}
var file_potentiometer_potentiometer_proto_depIdxs = []int32{
	2, // 0: Potentiometer.Potentiometer.finger:type_name -> Shared.Finger
	0, // 1: Potentiometer.Potentiometer.positoin:type_name -> Potentiometer.Position
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_potentiometer_potentiometer_proto_init() }
func file_potentiometer_potentiometer_proto_init() {
	if File_potentiometer_potentiometer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_potentiometer_potentiometer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Potentiometer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_potentiometer_potentiometer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_potentiometer_potentiometer_proto_goTypes,
		DependencyIndexes: file_potentiometer_potentiometer_proto_depIdxs,
		EnumInfos:         file_potentiometer_potentiometer_proto_enumTypes,
		MessageInfos:      file_potentiometer_potentiometer_proto_msgTypes,
	}.Build()
	File_potentiometer_potentiometer_proto = out.File
	file_potentiometer_potentiometer_proto_rawDesc = nil
	file_potentiometer_potentiometer_proto_goTypes = nil
	file_potentiometer_potentiometer_proto_depIdxs = nil
}
